export const GET_MARKET_START = "@GET_MARKET_START";
export const GET_MARKET_SUCCESS = "@GET_MARKET_SUCCESS";
export const GET_MARKET_FAILED = "@GET_MARKET_FAILED";

export const SIGNALR_MARKET_CONNECT_START = "@SIGNALR_MARKET_CONNECT_START";
export const SIGNALR_MARKET_CONNECT_SUCCESS = "@SIGNALR_MARKET_CONNECT_SUCCESS";
export const SIGNALR_MARKET_CONNECT_FAILED = "@SIGNALR_MARKET_CONNECT_FAILED";

export const SIGNALR_MARKET_DISCONNECTED = "@SIGNALR_MARKET_DISCONNECTED";
export const SIGNALR_MARKET_RECONNECTED = "@SIGNALR_MARKET_RECONNECTED";
