export const GET_ALL_NEWS_START = '@GET_ALL_NEWS_START';
export const GET_ALL_NEWS_SUCCESS = '@GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_FAILED = '@GET_ALL_NEWS_FAILED';

export const NEWS_AUTHOR = '@NEWS_AUTHOR';
