export const PORTFOLIO_IS_EMPTY = "@PORTFOLIO_IS_EMPTY";

export const PORTFOLIO_DELETE_START = "@PORTFOLIO_DELETE_START";
export const PORTFOLIO_DELETE_SUCCESS = "@PORTFOLIO_DELETE_SUCCESS";
export const PORTFOLIO_DELETE_FAIL = "@PORTFOLIO_DELETE_FAIL";

export const SIGNALR_CONNECT_SUCCESS_PDATA = "@SIGNALR_CONNECT_SUCCESS_PDATA";
export const SIGNALR_CONNECT_SUCCESS_CLİST = "@SIGNALR_CONNECT_SUCCESS_CLİST";
export const SIGNALR_CONNECT_SUCCESS_CDATA = "@SIGNALR_CONNECT_SUCCESS_CDATA";

export const SIGNALR_CONNECT_SUCCESS_COIN_DETAIL =
  "@SIGNALR_CONNECT_SUCCESS_COIN_DETAIL";
export const SIGNALR_CONNECT_SUCCESS_COIN_DETAIL_CHART =
  "@SIGNALR_CONNECT_SUCCESS_COIN_DETAIL_CHART";
export const SIGNALR_CONNECT_SUCCESS_COIN_DETAIL_FAILED =
  "@SIGNALR_CONNECT_SUCCESS_COIN_DETAIL_FAILED";

export const GET_PORTFOLIO_ID_SUCCESS = "@GET_PORTFOLIO_ID_SUCCESS";
export const GET_PORTFOLIO_ID_FAILED = "@GET_PORTFOLIO_ID_FAILED";

export const GET_PORTFOLIO_ALL_ITEMS_SUCCESS =
  "@GET_PORTFOLIO_ALL_ITEMS_SUCCESS";
export const GET_PORTFOLIO_ALL_ITEMS_FAILED = "@GET_PORTFOLIO_ALL_ITEMS_FAILED";

export const PORTFOLIO_ADD_START = "@PORTFOLIO_ADD_START";
export const PORTFOLIO_ADD_SUCCESS = "@PORTFOLIO_ADD_SUCCESS";
export const PORTFOLIO_ADD_FAIL = "@PORTFOLIO_ADD_FAIL";

export const ALL_PORTFOLIOS_SUCCESS = "@ALL_PORTFOLIOS_SUCCESS";
export const ALL_PORTFOLIOS_FAIL = "@ALL_PORTFOLIOS_FAIL";

export const PORTFOLIO_COIN_DELETE_SUCCESS = "@PORTFOLIO_COIN_DELETE_SUCCESS";
export const PORTFOLIO_COIN_DELETE_FAIL = "@PORTFOLIO_COIN_DELETE_FAIL";

export const PORTFOLIO_COIN_ADD_SUCCESS = "@PORTFOLIO_COIN_ADD_SUCCESS";
export const PORTFOLIO_COIN_ADD_FAIL = "@PORTFOLIO_COIN_ADD_FAIL";

export const SET_CURRENT_PORTFOLIO_ID = "@SET_CURRENT_PORTFOLIO_ID";
export const SET_CURRENT_PORTFOLIO_NAME = "@SET_CURRENT_PORTFOLIO_NAME";

export const SIGNALR_DISCONNECTED = "@SIGNALR_DISCONNECTED";
export const SIGNALR_RECONNECTED = "@SIGNALR_RECONNECTED";

export const SIGNALR_CONNECT_START = "@SIGNALR_CONNECT_START";
export const SIGNALR_CONNECT_SUCCESS = "@SIGNALR_CONNECT_SUCCESS";
export const SIGNALR_CONNECT_FAILED = "@SIGNALR_CONNECT_FAILED";
